FROM golang:1.17-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY ./sender/main.go .

# variables de entorno para el build de la imagen del sender
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

RUN go build -ldflags="-s -w" -o sender .

FROM scratch


COPY --from=builder ["/build/sender", "/"]

# Commando a ejecutar al iniciar el contenedor
ENTRYPOINT ["/sender"]